name: ci
on: push
jobs:
  record-mode:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Record responses
        uses: cypress-io/github-action@v6
        with:
          start: npm start
        env:
          # record all API calls
          CYPRESS_magic_backend_mode: recording

      - name: Show changes JSON files
        run: git status

  playback-mode:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cypress against static backend
        uses: cypress-io/github-action@v6
        with:
          start: npm run start:static
        env:
          # assume that all backend calls to "/todos" are pre-recorded
          # in the cypress/magic-backend folder
          # and on CI the API backend should be in playback mode
          # and completely stubbed
          CYPRESS_magic_backend_mode: playback

  inspect-mode:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Inspecting against real backend
        uses: cypress-io/github-action@v6
        with:
          start: npm start
        env:
          # assume the real backend is available
          # allows each call to go to the real backend
          # but compares the request and response to the
          # recorded api calls from JSON files
          CYPRESS_magic_backend_mode: inspect
